### ISSUE TITLE
Unknown ROM version on attempted data.rom extraction

### ISSUE THREAD

**Issue by doqfgc** [DCNick3/shin-translation-tools#2]
**Error**: `Unknown ROM version: [212, 40, 22, 249, 89, 29, 146, 115]`

**Game details**:
Name: ALIA'sCARNIVAL! サクラメント (ALIA's CARNIVAL! Sacrament)
Developer: NanaWind
Publisher: Dramatic Create
Platform: psvita
Release date: 2015-10-29

<details>

<summary>Short Backtrace</summary>

```
2024-03-30T20:15:29.143592Z  INFO shin_rom::extract: Extracting "data.rom" to "data-dir"
thread 'main' panicked at shin-versions/src/lib.rs:167:21:
Unknown ROM version: [212, 40, 22, 249, 89, 29, 146, 115]
stack backtrace:
   0: rust_begin_unwind
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
   2: shin_versions::RomVersion::detect
   3: shin_rom::extract::rom_extract
   4: shin_tl::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</details>

---

I've noticed that this title is significantly older than other dramatic create titles on the compatibility list, wonder if it's an older format version.

**Comment by DCNick3** [comment]
I think what is happening here is that you have not actually decrypted the game (there is a dump format where all the file structure is there, but the actual contents are still encrypted. The header bytes seem to correspond to the encrypted ones. 

This might be helpful: https://github.com/TheRadziu/NoNpDRM-modding/wiki#obtaining-decrypted-game-assets-from-nonpdrm-rips-through-vitashell-decryption-on-console

**Comment by DCNick3** [comment]
Please let me know if this is still an issue for you

**Comment by doqfgc** [comment]
Huh. Figured VitaShell would do it automatically, but I guess I need to be smarter than the software. Though I did wonder why the PNGs weren't loading, and now I know.

After following directions, tool worked as intended.

Closed: user error.
